/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_admin (void);
GtkWidget* create_adherent1 (void);
GtkWidget* create_home (void);
GtkWidget* create_coach (void);
GtkWidget* create_adherantnotvalid (void);
GtkWidget* create_error (void);
